name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - main  # deploy khi có push lên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # cấp quyền ghi để push lên gh-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build project
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
