name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main   # hoặc master nếu repo bạn dùng master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend   # 👈 chạy trong thư mục frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend   # 👈 build trong thư mục frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist   # 👈 dist nằm trong frontend

